### PR TITLE
first tests

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa @scottwittenburg @muryanto1 please review. Mainly brings recipe in, switches to setuptool and use "noarch" for uploading (which saves time and space)

**Comment by doutriaux1** [comment]
@muryanto1 it also fixes bug in nightly/master

**Comment by doutriaux1** [comment]
@muryanto1 looks like i need something else to trigger coverage

**Comment by doutriaux1** [comment]
@muryanto1 thx. So we have coverage but we dont... Same issue as pmp all tests here are ran as subprocesses...

**Comment by doutriaux1** [comment]
@danlipsa can i merge this in?

**Comment by danlipsa** [comment]
Looks good to me. I can rebase on my branch.

**Comment by doutriaux1** [comment]
@danlipsa mostly moved file around it should be an easy merge.

**Pull request merged**
